# To use:
#
#   $ conda env create -f environment.yaml
#   $ conda activate exploring-interventions
#

name: exploring-interventions
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - flake8
  - black
  - tqdm
  - pandas
  - requests
  - openpyxl
  - xlrd
